import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Container from "./components/container";
import Header from "./components/header";
import Footer from "./components/footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <meta
          name="viewport"
          content="width=device-width,height=device-height, initial-scale=1.0"
        />
      </head>
      <body className={inter.className}>
        <Header />
        <main className="pt-navigation-height bg-gradient-radial">{children} </main>
        <Footer />
      </body>
    </html>
  );
}
